"""product table  updated migration here

Revision ID: 7005cb80cd6b
Revises: f9f1a626f0af
Create Date: 2025-04-20 04:25:11.627032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7005cb80cd6b'
down_revision: Union[str, None] = 'f9f1a626f0af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_name', sa.String(), nullable=False))
    op.drop_column('products', 'productName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('productName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('products', 'product_name')
    # ### end Alembic commands ###
