"""Change variable name migration here

Revision ID: ebda7a7e370c
Revises: 18cc4821020a
Create Date: 2025-04-20 03:44:45.534194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebda7a7e370c'
down_revision: Union[str, None] = '18cc4821020a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pwd', sa.String(), nullable=False))
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('urole', sa.String(), nullable=False))
    op.add_column('users', sa.Column('picture', sa.Text(), nullable=True))
    op.drop_column('users', 'password')
    op.drop_column('users', 'profilePicture')
    op.drop_column('users', 'createdDate')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('createdDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profilePicture', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'picture')
    op.drop_column('users', 'urole')
    op.drop_column('users', 'created')
    op.drop_column('users', 'pwd')
    # ### end Alembic commands ###
