"""education level updated migration here

Revision ID: f9f1a626f0af
Revises: ebda7a7e370c
Create Date: 2025-04-20 03:50:54.076979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f1a626f0af'
down_revision: Union[str, None] = 'ebda7a7e370c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('levelofeducation', sa.String(), nullable=False))
    op.drop_column('users', 'levelOfEducation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('levelOfEducation', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'levelofeducation')
    # ### end Alembic commands ###
